### ISSUE TITLE
MSVCP140.dll missing from your computer error

### ISSUE THREAD

**Issue by Finetuned** [forrest79/removebom#1]
I've started seeing this error in some vanilla versions of Windows 7 Enterprise SP1.
Sideloading the missing dlls (below)  by placing them in the same directory seems to work…

`MSVCP140.dll` &  `VCRUNTIME140.dll`

**Comment by forrest79** [comment]
Hello, you need Visual C++ Redistributable for Visual Studio XYZ, for example 2015 (https://www.microsoft.com/en-us/download/details.aspx?id=48145) if you're compiling source code with Visual Studio 2015.

**Comment by Finetuned** [comment]
I know, it would just be preferable to avoid installing the redist.

**Comment by forrest79** [comment]
I don't know if VS can do static compilation with libraries, but I provide only source codes, it's up to you, how to compile it...
